#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

number=0
while [ $number -lt 10 ]
 do
	if [ $number -eq 3 ]
	then
	echo "bad luck"
	elif [ $number -eq 7 ]
	then
	echo "good luck"
	else
	echo "Best School"
	fi
	(( number++ ))
 done
